### PR TITLE
database items

### PR DESCRIPTION
**Pull request by bluesheepllama**
-a csv file for database items from Lighthouse cafe and Pizza 3.14
- LH Cafe items are from a blurry photo so i may need to go in there and look at the menu 
-could find menus for other places so i will need to go investigate

### CODE REVIEW

**Comment by kelseyp** [comment]
Just for confirmation, is this data in the format best fitting our chosen database and are all the necessary columns included? I just want to know that this file is ready to go for import once the database is initialized.

**Comment by bluesheepllama** [comment]
> Just for confirmation, is this data in the format best fitting our chosen database and are all the necessary columns included? I just want to know that this file is ready to go for import once the database is initialized.

from what i looked into, csv file is a good way to go with mangodb as far as columns go, that should probably be discussed tonight

**Review by kelseyp — APPROVED** [review]

**Comment by NathanaelPaulus** [comment]
This looks great. I think we have a really good trajectory off the back of this!

**Review by NathanaelPaulus — APPROVED** [review]
approve

**Pull request merged**
