### PR TITLE
Adding a drawer to the left side of the app

### PR DESCRIPTION
**Pull request by NathanaelPaulus**
Added a drawer to hold future filtering options. Included are 1 filter icon and the word filter.

### CODE REVIEW

**Review by bluesheepllama — DISMISSED** [review]
looks good

**Comment by austinhedrick548** [comment]
Had trouble running without having to install the icons-material package, installed and committed the package changes so we dont have to do that every time

**Review by austinhedrick548 — APPROVED** [review]
Looks good from my codespace

**Review by bluesheepllama — APPROVED** [review]
looks good

**Pull request merged**
